# ***** BEGIN LICENCE BLOCK *****
# Version: CePL 1.1
# 
# The contents of this file are subject to the Celtx Public License
# Version 1.1 (the "License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.celtx.com/CePL/
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is Celtx Script Manager.
# 
# The Initial Developer of the Original Code is Chad House and 4067479
# Canada Inc. t/a CELTX.
# 
# Portions created by Chad House are Copyright (C) 2000-2005 Chad House,
# parts created by Celtx are Copyright (C) 4067479 Canada Inc. All Rights
# Reserved.
# 
# Contributor(s):
#
# ***** END LICENCE BLOCK *****

  <script type="application/x-javascript"
          src="chrome://global/content/globalOverlay.js"/>
  <script type="application/x-javascript"
          src="chrome://global/content/nsDragAndDrop.js"/>
  <script type="application/x-javascript"
          src="chrome://global/content/nsTransferable.js"/>
  <script type="application/x-javascript"
          src="chrome://global/content/printUtils.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/util.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/guiutils.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/rdfmodel.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/project.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/importer.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/printing.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/scriptstyle.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/app.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/scriptds.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/searchbar.js"/>
  <script type="application/x-javascript"
          src="chrome://celtx/content/macmenus.js"/>

